Repository wecode-bootcamp-korea/bang_olaf-frontend, pull requests merged in 2021-01, with the labels that each got.

#2 [16기 정선미] Login 레이아웃 및 기능 구현
  package-lock.json
  package.json
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/components/LoginFooter.js
  src/Pages/Login/components/LoginFooter.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Routes.js
  src/config.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#5 [16기 정선미] Account 레이아웃 및 기능 구현
  src/Pages/Account/Account.js
  src/Pages/Account/Account.scss
  src/Pages/Account/components/AccountFooter.js
  src/Pages/Account/components/AccountFooter.scss
  src/Pages/Basket/basket.js
  src/Pages/Basket/basket.scss
  src/config.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: Accepted

#7 [16기 정선미] Account footer 번역기 컴포넌트화 및 map 사용
  src/Pages/Account/Account.js
  src/Pages/Account/Account.scss
  src/Pages/Account/components/AccountFooter.js
  src/Pages/Account/components/AccountFooter/AccountFooter.js
  src/Pages/Account/components/AccountFooter/AccountFooter.scss
  src/Pages/Account/components/AccountFooter/LanguageOptionList.js
  src/Pages/Account/components/AccountFooter/LanguageOptionList.scss
  src/Pages/Account/components/AccountFooter/Languagedata.js
Labels: Status: 리뷰 요청

#6 [16기 김기열] ProductDetail 레이아웃 구성 완료 & 리팩토링 & 리뷰 반영 완료
  debug.log
  package-lock.json
  package.json
  public/data/ProductsData.json
  src/Components/Button/BuyButton.js
  src/Components/Button/BuyButton.scss
  src/Components/Footer/Footer.scss
  src/Pages/ProductDetail/Components/Features/Features.js
  src/Pages/ProductDetail/Components/Features/Features.scss
  src/Pages/ProductDetail/Components/Features/FeaturesBox.js
  src/Pages/ProductDetail/Components/Features/FeaturesContainer.js
  src/Pages/ProductDetail/Components/Features/FeaturesGallery.js
  src/Pages/ProductDetail/Components/Features/FeaturesInfo.js
  src/Pages/ProductDetail/Components/Features/FeaturesResponsive.js
  src/Pages/ProductDetail/Components/Inspirations/Inspirations.js
  src/Pages/ProductDetail/Components/Inspirations/Inspirations.scss
  src/Pages/ProductDetail/Components/ProductDetailNavbar.js
  src/Pages/ProductDetail/Components/ProductDetailNavbar.scss
  src/Pages/ProductDetail/Components/ProductSpec/ProductSpec.js
  src/Pages/ProductDetail/Components/ProductSpec/ProductSpec.scss
  src/Pages/ProductDetail/Components/Summary.js
  src/Pages/ProductDetail/Components/Summary/SimpleSlider.js
  src/Pages/ProductDetail/Components/Summary/Summary.js
  src/Pages/ProductDetail/Components/Summary/Summary.scss
  src/Pages/ProductDetail/Components/Summary/SummaryAttribute.js
  src/Pages/ProductDetail/Components/Summary/SummaryContent.js
  src/Pages/ProductDetail/Components/Summary/_Slick-theme.scss
  src/Pages/ProductDetail/Components/Summary/_Slick.scss
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Routes.js
  src/config.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#10 [16기 김기열] navbar 경로 수정
  src/Components/Navbar/CommonNavbar.js
Labels: Status: Accepted

#3 [16기 정재윤] 데이터 통신 완료/ 카테고리 클릭 시 다른 데이터 받아 오기 완료/ confif.js 충돌 해결
  package-lock.json
  public/data/data.json
  public/data/data1.json
  public/images/1.png
  public/images/logo.jpeg
  public/index.html
  public/robots.txt
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Pages/ProductList/components/CategoryList.js
  src/Pages/ProductList/components/CategoryList.scss
  src/Pages/ProductList/components/NavList.js
  src/Pages/ProductList/components/NavList.scss
  src/Pages/ProductList/components/NavListTitle.js
  src/Pages/ProductList/components/NavListTitle.scss
  src/Pages/ProductList/components/ProductCard.js
  src/Pages/ProductList/components/ProductCard.scss
  src/Pages/ProductList/components/ProductListContainer.js
  src/Pages/ProductList/components/ProductListContainer.scss
  src/Pages/ProductList/components/VideoContainer.js
  src/Pages/ProductList/components/VideoContainer.scss
  src/Pages/ProductList/components/navdata.js
  src/Routes.js
  src/config.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#12 [16기 정재윤] 동적라우팅 기능 구현 확인
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/components/ProductCard.js
  src/Routes.js
  src/config.js
Labels: Status: 추가 기능 구현중

#9 [16기 정선미] Account 수정
  public/data/accountFooter.json
  src/Pages/Account/Account.js
  src/Pages/Account/Account.scss
  src/Pages/Account/components/AccountFooter.js
  src/Pages/Account/components/AccountFooter/AccountFooter.scss
Labels: Status: 리뷰 요청

#11 [16기 정선미] Login 수정
  src/Components/Navbar/CommonNavbar.js
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/components/LoginFooter.scss
  src/config.js
Labels: Status: 리뷰 요청
